openapi: 3.0.2
info:
  version: ''
  title: 'Skilningur'
  description: 'Educational meeting platform'

paths:
  /:
    get:
      responses:
        200:
          description: ok

components:
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      description: call /login to get token
      bearerFormat: JWT

servers:
  - description: localhost
    url: http://localhost:8080